import {test} from 'node:test';
import assert from 'node:assert/strict';
import {registrationMessage,registrationMailConfig,sendRegistrationEmail} from '../lib/registration-email';
const env={SMTP_HOST:'smtp.example.test',SMTP_USER:'test',SMTP_PASS:'test',SMTP_FROM:'noreply@example.test',APP_URL:'https://prisma.example.test'};
test('email berisi NIK, password, tautan login, dan status disetujui',()=>{const m=registrationMessage({name:'Nama <Anggota>',email:'member@example.test',username:'3271000000000001',password:'Example<&>123!'},env.APP_URL);assert.deepEqual(m.to,{name:'Nama <Anggota>',address:'member@example.test'});assert.ok(m.text.includes('Username (NIK): 3271000000000001'));assert.ok(m.text.includes('Kata sandi: Example<&>123!'));assert.ok(m.text.includes('https://prisma.example.test/login/anggota'));assert.ok(m.text.includes('telah disetujui'));assert.ok(!m.text.includes('menunggu verifikasi'));assert.equal('html' in m,false)});
test('SMTP memakai TLS dan konfigurasi lengkap',()=>{const c=registrationMailConfig(env);assert.equal(c.transport.requireTLS,true);assert.equal(c.transport.secure,false);assert.equal(registrationMailConfig({...env,SMTP_PORT:'465'}).transport.secure,true);assert.throws(()=>registrationMailConfig({}));assert.throws(()=>registrationMailConfig({...env,SMTP_PORT:'abc'}));assert.throws(()=>registrationMailConfig({...env,APP_URL:'javascript:alert(1)'}))});
test('kegagalan konfigurasi tidak melempar atau mencatat kata sandi',async()=>{const old=process.env.SMTP_HOST;const log=console.error;const messages:string[]=[];delete process.env.SMTP_HOST;console.error=(...args)=>messages.push(args.join(' '));try{assert.equal(await sendRegistrationEmail({name:'Test',email:'test@example.test',username:'123',password:'SecretNotLogged123'}),false);assert.equal(messages.length,1);assert.ok(!messages[0].includes('SecretNotLogged123'))}finally{console.error=log;if(old===undefined)delete process.env.SMTP_HOST;else process.env.SMTP_HOST=old}});

test('SMTP menolak host salah dan mendukung Outlook OAuth2',()=>{assert.throws(()=>registrationMailConfig({...env,SMTP_HOST:'://office365.com'}));assert.throws(()=>registrationMailConfig({...env,SMTP_PORT:'587',SMTP_SECURE:'true'}));assert.throws(()=>registrationMailConfig({...env,SMTP_AUTH_TYPE:'oauth2'}));const c=registrationMailConfig({...env,SMTP_AUTH_TYPE:'oauth2',SMTP_ACCESS_TOKEN:'test-token'});assert.equal(c.transport.auth?.type,'OAuth2')});
