"use client";
import {useEffect,useRef,useState} from "react";
import QRCode from "qrcode";
import {membershipLabel,regionLabel} from "@/lib/membership";
export function MemberCard({member:m}:{member:any}){
 const organizationName=m.organizationName?.trim()||"PRISMA";
 const organizationFontSize=organizationName.length>40?12:organizationName.length>20?16:organizationName.length>14?18:23;
 const ref=useRef<HTMLDivElement>(null);const [qr,setQr]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{if(m.memberNo)QRCode.toDataURL(window.location.origin+"/verifikasi/"+encodeURIComponent(m.memberNo),{width:280,margin:4,errorCorrectionLevel:"M"}).then(setQr).catch(()=>setError("QR gagal dibuat."))},[m.memberNo]);
 async function download(){if(!ref.current)return;setBusy(true);setError("");try{await document.fonts.ready;const {toPng}=await import("html-to-image");const {jsPDF}=await import("jspdf");const png=await toPng(ref.current,{pixelRatio:3,cacheBust:true});const pdf=new jsPDF({orientation:"landscape",unit:"mm",format:[85.6,53.98]});pdf.addImage(png,"PNG",0,0,85.6,53.98);pdf.save("KTA-"+m.memberNo+".pdf")}catch{setError("PDF gagal dibuat. Pastikan foto dan QR sudah termuat, lalu coba lagi.")}finally{setBusy(false)}}
 return <><div className="mt-5 overflow-x-auto pb-2"><div ref={ref} className="member-card" style={{width:480,height:303,position:"relative",overflow:"hidden",borderRadius:18,background:"linear-gradient(125deg,#0f172a 0%,#123b62 65%,#087e8b 100%)",color:"white",padding:25,fontFamily:"Arial, sans-serif"}}>
 <div style={{position:"absolute",width:230,height:230,border:"40px solid rgba(34,211,238,.10)",borderRadius:"50%",right:-65,top:-95}}/>
 <header style={{display:"flex",justifyContent:"space-between",alignItems:"center",position:"relative",gap:8}}><div style={{display:"flex",alignItems:"center",gap:10,minWidth:0,flex:1}}>{m.logoUrl&&<img src={m.logoUrl} alt={`Logo ${organizationName}`} style={{width:42,height:42,objectFit:"contain",borderRadius:6,background:"white",flexShrink:0}}/>}<div style={{maxWidth:250,minWidth:0}}><strong style={{display:"block",fontSize:organizationFontSize,letterSpacing:organizationName.length>20?0:organizationName.length>14?1:2,lineHeight:1.15,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{organizationName}</strong><div style={{fontSize:8,letterSpacing:2,color:"#a5f3fc",marginTop:4}}>KARTU TANDA ANGGOTA</div></div></div><span style={{fontSize:10,padding:"6px 10px",borderRadius:20,background:m.status==="active"?"#065f46":"#334155",flexShrink:0}}>{m.status==="active"?"AKTIF":"TIDAK AKTIF"}</span></header>
 <div style={{display:"flex",gap:18,marginTop:23,position:"relative"}}>{m.photoUrl?<img src={m.photoUrl} alt="Foto anggota" style={{width:78,height:99,objectFit:"cover",borderRadius:10,border:"2px solid #67e8f9"}}/>:<div style={{width:78,height:99,borderRadius:10,background:"#334155",display:"grid",placeItems:"center",fontSize:30,flexShrink:0}}>{m.name?.slice(0,1)}</div>}
 <div style={{minWidth:0,flex:1,maxWidth:235}}><div style={{fontSize:m.name.length>55?13:m.name.length>30?16:18,fontWeight:700,lineHeight:1.15,overflowWrap:"anywhere"}}>{m.name}</div><div style={{fontSize:12,letterSpacing:1,color:"#a5f3fc",marginTop:7}}>{m.memberNo||"NOMOR BELUM TERBIT"}</div><div style={{fontSize:11,lineHeight:1.3,marginTop:8,overflowWrap:"anywhere"}}><span style={{color:"#cbd5e1"}}>Jabatan: </span><strong>{m.position?.trim()||"Anggota"}</strong></div><div style={{fontSize:10,marginTop:8,color:"#cbd5e1"}}>{membershipLabel(m)}{membershipLabel(m)==="Cabang"?" • "+m.branchType:""}</div><div style={{fontSize:11,lineHeight:1.3,marginTop:4,maxWidth:220}}>{regionLabel(m)}</div></div></div>
 <footer style={{position:"absolute",bottom:20,left:25,right:25,display:"flex",justifyContent:"space-between",alignItems:"end"}}><div style={{fontSize:9,color:"#a5f3fc",lineHeight:1.3,maxWidth:320,overflowWrap:"anywhere"}}><span style={{display:"block",marginTop:5,color:"#cbd5e1",letterSpacing:0}}>Pindai QR untuk memeriksa status terkini</span></div>{qr?<img src={qr} alt="QR verifikasi anggota" width={78} height={78} style={{borderRadius:5}}/>:<span style={{fontSize:9}}>QR tersedia setelah nomor terbit</span>}</footer>
 </div></div>{!m.memberNo&&<p className="mt-2 text-sm text-amber-700">Pendaftaran pending. Kartu dan QR tersedia setelah disetujui.</p>}{m.memberNo&&<button onClick={download} disabled={busy||!qr} className="btn-secondary mt-4 w-full">{busy?"Menyiapkan PDF...":"Unduh PDF Kartu • 85,6 × 53,98 mm"}</button>}{error&&<p role="alert" className="mt-2 text-sm text-rose-600">{error}</p>}</>;
}
